#### Tensorflow 6강. File load in Tensorflow and Queue Thread
##### https://www.youtube.com/watch?v=hPkmxczEj6k&index=6&list=PL1H8jIvbSo1qOtjQXFzBxMWjL_Gc5x3yG&t=940s

In [6]:
import tensorflow as tf
import os
from PIL import Image

In [7]:
image_dir=os.getcwd()+"/images.jpeg"
filename_list=[image_dir]

filename_queue = tf.train.string_input_producer(filename_list)

In [8]:
reader = tf.WholeFileReader()
key, value = reader.read(filename_queue)

In [9]:
image =tf.image.decode_png(value)

In [10]:
with tf.Session() as sess:
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=sess, coord=coord)    
    
    image = sess.run(image)
    print(image)
    
    coord.request_stop()
    coord.join(threads)

[[[65]
  [68]
  [64]
  ..., 
  [ 6]
  [27]
  [58]]

 [[75]
  [74]
  [61]
  ..., 
  [33]
  [36]
  [35]]

 [[48]
  [47]
  [44]
  ..., 
  [40]
  [39]
  [31]]

 ..., 
 [[ 2]
  [ 0]
  [ 0]
  ..., 
  [69]
  [22]
  [ 0]]

 [[ 6]
  [ 6]
  [ 0]
  ..., 
  [25]
  [ 8]
  [ 2]]

 [[10]
  [12]
  [ 4]
  ..., 
  [ 0]
  [ 0]
  [ 0]]]
INFO:tensorflow:Error reported to Coordinator: <class 'RuntimeError'>, Attempted to use a closed Session.


TypeError: Cannot handle this data type