#### Tensorflow의 자료형
- placeholder : input 데이터를 담아주는 공간(data, image, text등)
- Variabe : 객체 weight 파라미터 메트릭스 저장할때 사용 : 반드시 초기화가 필요한 자료형
- constant : 변하지 않는 수

In [5]:
import tensorflow as tf
ph = tf.placeholder(dtype=tf.float32, shape=[3,3])
var = tf.Variable([1,2,3,4,5], dtype=tf.float32)
const = tf.constant([10,20,30,40,50], dtype=tf.float32)

In [11]:
# 일반적으로 연산한 결과를 볼 수 없다.
print(const)

Tensor("Const_1:0", shape=(5,), dtype=float32)


In [17]:
a = tf.constant([5])
b = tf.constant([10])
c = tf.constant([2])
d= a*b+c
sess = tf.Session()
result=sess.run(d)
print(result)

[52]


In [21]:
var1 = tf.Variable([5])
var2 = tf.Variable([3])
var3 = tf.Variable([2])

var4= var1*var2+var3
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result=sess.run(var4)
print(result)
# 초기화 해야 됨.

[17]


In [22]:
#placeholder 그래프 만들지 않음. 텐서와 데이터만 맵핑함. feeding해줘야함.
value1 = 5
value2 = 3
value3 = 2
ph1 = tf.placeholder(dtype=tf.float32)
ph2 = tf.placeholder(dtype=tf.float32)
ph3 = tf.placeholder(dtype=tf.float32)
# key, value 로 맵핑함
result_value = ph1 * ph2 + ph3
feed_dict = {ph1:value1, ph2:value2, ph3:value3}

sess= tf.Session()
result=sess.run(result_value, feed_dict=feed_dict)
print(result)


17.0


In [25]:
#image =[1,2,3,4,5]
image =[[1,2,3,4,5],[5,4,3,2,1],[10,20,30,40,50]]
lable =[10,20,30,40,50]
ph_image = tf.placeholder(dtype=tf.float32)
ph_label = tf.placeholder(dtype=tf.float32)
feed_dict = {ph_image:image, ph_label:lable}

result_tensor= ph_image + ph_label
sess= tf.Session()
result=sess.run(result_tensor, feed_dict=feed_dict)
print(result)

[[  11.   22.   33.   44.   55.]
 [  15.   24.   33.   42.   51.]
 [  20.   40.   60.   80.  100.]]
